### ISSUE TITLE
Confusing error messages on failed date-coercion in series selection.

### ISSUE THREAD

**Issue by philipmassouh** [static-frame/static-frame#1006]
**Description**

Using `__getitem__` on a date-index `Series` results in a confusing error message, please improve the error message.

**Example**
```python
import static_frame as sf
sf.Series(range(12), index=sf.IndexYearMonth.from_year_month_range("2024-01", "2024-12"))["not a date"]
```
error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/massouh/.env311/lib/python3.11/site-packages/static_frame/core/series.py", line 1963, in __getitem__
    return self._extract_loc(key)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/massouh/.env311/lib/python3.11/site-packages/static_frame/core/series.py", line 1944, in _extract_loc
    iloc_key = self._index._loc_to_iloc(key)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/massouh/.env311/lib/python3.11/site-packages/static_frame/core/index_datetime.py", line 161, in _loc_to_iloc
    return Index._loc_to_iloc(self,
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/massouh/.env311/lib/python3.11/site-packages/static_frame/core/index.py", line 887, in _loc_to_iloc
    key = key_transform(key)
          ^^^^^^^^^^^^^^^^^^
  File "/home/massouh/.env311/lib/python3.11/site-packages/static_frame/core/util.py", line 2245, in key_to_datetime_key
    return to_datetime64(key, dtype=dtype) # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/massouh/.env311/lib/python3.11/site-packages/static_frame/core/util.py", line 2176, in to_datetime64
    dt = np.datetime64(value) # type: ignore
         ^^^^^^^^^^^^^^^^^^^^
ValueError: Error parsing datetime string "not a date" at position 0
```

**Platform**
```
<Series: platform>
<Index>
platform           Linux-6.8.0-50-generic-x86_64-with-glibc2.39
sys.version        3.11.4 (main, Oct  9 2024, 14:04:49) [GCC 13.2.0]
static-frame       2.15.1
numpy              1.24.3
pandas             1.5.3
xlsxwriter         3.1.0
openpyxl           3.0.9
xarray             <ModuleNotFoundError>
tables             3.8.0
pyarrow            12.0.1
msgpack            None
msgpack_numpy      None
<<U13>             <object>
```

**Comment by flexatone** [comment]
Agreed! Thanks for isolating this.
