### ISSUE TITLE
`NotImplementedError` instead of `KeyError` on Column Retrieval

### ISSUE THREAD

**Issue by philipmassouh** [static-frame/static-frame#657]
**Description**

`NotImplementedError` instead of a `KeyError` when trying to retrieve columns from a `Frame`.

**Example**

```python
import frame_fixtures as ff
ff.parse('v(bool,str,bool,float)|s(4,8)')["foo"]
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/massouh/.env38/lib/python3.8/site-packages/static_frame/core/frame.py", line 4653, in __getitem__
    return self._extract(*self._compound_loc_to_getitem_iloc(key))
  File "/home/massouh/.env38/lib/python3.8/site-packages/static_frame/core/frame.py", line 4519, in _extract
    blocks = self._blocks._extract(row_key=row_key, column_key=column_key)
  File "/home/massouh/.env38/lib/python3.8/site-packages/static_frame/core/type_blocks.py", line 2807, in _extract
    return self.from_blocks(
  File "/home/massouh/.env38/lib/python3.8/site-packages/static_frame/core/type_blocks.py", line 336, in from_blocks
    for block in raw_blocks:
  File "/home/massouh/.env38/lib/python3.8/site-packages/static_frame/core/type_blocks.py", line 2611, in _slice_blocks
    for block_idx, slc in self._key_to_block_slices(column_key): # PERF: most time from line profiler
  File "/home/massouh/.env38/lib/python3.8/site-packages/static_frame/core/type_blocks.py", line 1516, in _key_to_block_slices
    raise NotImplementedError('Cannot handle key', key)
NotImplementedError: ('Cannot handle key', 'foo')
```

**Platform**

```
<Series: platform>
<Index>
platform           Linux-5.14.0-1052-oem-x86_64-with-glibc2.29
sys.version        3.8.12 (default, Aug 22 2022, 10:56:44) [GCC 9.3.0]
static-frame       0.9.17
numpy              1.19.2
pandas             0.25.3
xlsxwriter         1.1.5
openpyxl           3.0.9
xarray             <ModuleNotFoundError>
tables             3.6.1
pyarrow            0.17.0
msgpack            (1, 0, 0)
msgpack_numpy      None
<<U13>             <object>
```

**Comment by flexatone** [comment]
Thanks for posting this issue; this will be corrected with the linked PR.
