### ISSUE TITLE
`ErrorInitIndex` When Calling `Frame.rehierarch`

### ISSUE THREAD

**Issue by michaeljpeters** [static-frame/static-frame#712]
**Description**

Calling `Frame.rehierarch` causes the following error:

```
Traceback (most recent call last):
  File "michael/core/pde/sf_fail.py", line 20, in <module>
    f.rehierarch((1, 0))
  File "/home/peters/.env38/lib/python3.8/site-packages/static_frame/core/frame.py", line 4477, in rehierarch
    index_idx, index_iloc = rehierarch_from_index_hierarchy(
  File "/home/peters/.env38/lib/python3.8/site-packages/static_frame/core/container_util.py", line 1024, in rehierarch_from_index_hierarchy
    return labels.__class__._from_type_blocks(
  File "/home/peters/.env38/lib/python3.8/site-packages/static_frame/core/index_hierarchy.py", line 913, in _from_type_blocks
    indices, indexers = construct_indices_and_indexers_from_column_arrays(
  File "/home/peters/.env38/lib/python3.8/site-packages/static_frame/core/index_hierarchy.py", line 197, in construct_indices_and_indexers_from_column_arrays
    indices.append(constructor(unique_values))
  File "/home/peters/.env38/lib/python3.8/site-packages/static_frame/core/index.py", line 349, in __init__
    raise ErrorInitIndex('Cannot create an Index with a datetime64 array; use an Index subclass (e.g. IndexDate) or supply an `index_constructors` argument')
static_frame.core.exception.ErrorInitIndex: Cannot create an Index with a datetime64 array; use an Index subclass (e.g. IndexDate) or supply an `index_constructors` argument
```

**Example**

Provide an interactive Python session, or Python code, to demonstrate the issue. Please keep example data to a minimum.

```python
import numpy as np
import static_frame as sf

f = sf.Frame.from_items(
    [("price", [2, 3, 4])],
    index=sf.IndexHierarchy.from_product(
        ["APPL"],
        sf.IndexDate(
            [
                np.datetime64("2022-01-01"),
                np.datetime64("2022-01-02"),
                np.datetime64("2022-01-03"),
            ]
        ),
    ),
)

print(f)

f.rehierarch((1, 0))
```

**Platform**

Run the following function (static-frame >= 0.8.1) and provide the results to define your platform and environment:

```python
>>> import static_frame as sf
>>> sf.Platform.display()
<Series: platform>
<Index>
platform           Linux-5.15.0-56-generic-x86_64-with-glibc2.29
sys.version        3.8.12 (default, Sep 22 2022, 16:39:49) [GCC 9.4.0]
static-frame       1.0.1
numpy              1.19.2
pandas             0.25.3
xlsxwriter         1.1.5
openpyxl           3.0.9
xarray             <ModuleNotFoundError>
tables             3.6.1
pyarrow            0.17.0
msgpack            (1, 0, 0)
msgpack_numpy      None
<<U13>             <object>
```

**Comment by flexatone** [comment]
On further reflection it is clear that his sort of `rehierarch` should automatically provide the correct `index_constructors`; I have implemented that, as well as exposing `index_constructors` arguments, permitting callers to optionally transform the Index type. 

The fix will be in the 1.0.2 release.
