### ISSUE TITLE
`iter_tuple` `constructor` missing support for Dataclasses.

### ISSUE THREAD

**Issue by philipmassouh** [static-frame/static-frame#728]
**Description**

`iter_tuple` does not work when a `dataclass` is passed to the `constructor` argument.

**Example**

```python
>>> import static_frame as sf
>>> import frame_fixtures as ff
>>> from dataclasses import dataclass
>>> from typing import NamedTuple
>>> f = ff.parse('s(3,2)|v(int,str)')
>>> tuple(f.iter_tuple(axis=1, constructor=tuple))
((-88017, 'zaji'), (92867, 'zJnC'), (84967, 'zDdR'))
>>> @dataclass
... class Foo:
...     number: int
...     string: str
... 
>>> tuple(f.iter_tuple(axis=1, constructor=Foo))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/massouh/.env38/lib/python3.8/site-packages/static_frame/core/node_iter.py", line 276, in __iter__
    yield from self._func_values()
  File "/home/massouh/.env38/lib/python3.8/site-packages/static_frame/core/frame.py", line 5532, in _axis_tuple
    yield from self._blocks.iter_row_tuples(key=None, constructor=constructor)
  File "/home/massouh/.env38/lib/python3.8/site-packages/static_frame/core/type_blocks.py", line 2926, in iter_row_tuples
    yield constructor(chainer(i))
TypeError: __init__() missing 1 required positional argument: 'string'
```

**Platform**

```python
<Series: platform>
<Index>
platform           Linux-5.14.0-1056-oem-x86_64-with-glibc2.29
sys.version        3.8.12 (default, Aug 22 2022, 10:56:44) [GCC 9.3.0]
static-frame       1.1.0
numpy              1.19.2
pandas             0.25.3
xlsxwriter         1.1.5
openpyxl           3.0.9
xarray             <ModuleNotFoundError>
tables             3.6.1
pyarrow            0.17.0
msgpack            (1, 0, 0)
msgpack_numpy      None
<<U13>             <object>
```

**Comment by flexatone** [comment]
Thanks for identifying this issue. Support for this will be added with the associated PR and released as part of the 1.2 release.
