### ISSUE TITLE
`Frame.relabel_shift_out` fails when the last remaining index is an `IndexDate`

### ISSUE THREAD

**Issue by michaeljpeters** [static-frame/static-frame#729]
**Description**

`Frame.relabel_shift_out` fails with `ErrorInitIndex` when the last remaining index is an `IndexDate`

**Example**

`example.csv`
```
date,currency,price
2022-01-01,USD,2.48
2022-01-02,USD,2.52
2022-01-03,USD,2.49
2022-01-04,USD,2.51
```

`example.py`
```python
import static_frame as sf

f = sf.Frame.from_csv(
    "./example.csv",
    dtypes=["datetime64[D]", str, float],
    index_depth=2,
    index_constructors=[sf.IndexDate, sf.Index],
)
print(f)
f.relabel_shift_out(1)  # ErrorInitIndex
```
```
$ python example.py
<Frame>
<Index>                price     <<U5>
<IndexHierarchy>
2022-01-01       USD   2.48
2022-01-02       USD   2.52
2022-01-03       USD   2.49
2022-01-04       USD   2.51
<datetime64[D]>  <<U3> <float64>
Traceback (most recent call last):
  File "example.py", line 10, in <module>
    f.relabel_shift_out(1)  # ErrorInitIndex
  File "/home/peters/.env38/lib/python3.8/site-packages/static_frame/core/frame.py", line 4426, in relabel_shift_out
    new_target = target_ctor( # type: ignore
  File "/home/peters/.env38/lib/python3.8/site-packages/static_frame/core/index.py", line 349, in __init__
    raise ErrorInitIndex('Cannot create an Index with a datetime64 array; use an Index subclass (e.g. IndexDate) or supply an `index_constructors` argument')
static_frame.core.exception.ErrorInitIndex: Cannot create an Index with a datetime64 array; use an Index subclass (e.g. IndexDate) or supply an `index_constructors` argument
```

**Platform**

Run the following function (static-frame >= 0.8.1) and provide the results to define your platform and environment:

```python
>>> import static_frame as sf
>>> sf.Platform.display()
<Series: platform>
<Index>
platform           Linux-5.15.0-58-generic-x86_64-with-glibc2.29
sys.version        3.8.12 (default, Sep 22 2022, 16:39:49) [GCC 9.4.0]
static-frame       1.1.0
numpy              1.19.2
pandas             0.25.3
xlsxwriter         1.1.5
openpyxl           3.0.9
xarray             <ModuleNotFoundError>
tables             3.6.1
pyarrow            0.17.0
msgpack            (1, 0, 0)
msgpack_numpy      None
<<U13>             <object>
```

**Comment by flexatone** [comment]
Thank you for isolating this issue. This will be corrected with the associated PR and included in the 1.2 release.
