### ISSUE TITLE
Flaky tests

### ISSUE THREAD

**Issue by flexatone** [static-frame/static-frame#877]
```--------------------------------- Hypothesis ----------------------------------

Falsifying example: test_frame_isin(

    f1=<Frame>

    <Index>   0                   1      -1     2      <int32>

    <Index>

    0.0       9223372036854775808 0      0      0

    1.0       0                   0      0      0

    -1.0      9223372036854775808 0      0      0

    2.0       9223372036854775808 0      0      0

    <float64> <uint64>            <int8> <int8> <int8>,

    self=<static_frame.test.property.test_frame.TestUnit testMethod=test_frame_isin>,

)



You can reproduce this example by temporarily adding @reproduce_failure('6.40.0', b'AXicY2ZmZMACkAQZEWwmBmYoDWKwQNjMICUQNQ2ougEOAwCi') as a decorator on your test case
```

**Comment by flexatone** [comment]
```
 ___________________________ TestUnit.test_setdiff1d ____________________________
Traceback (most recent call last):
  File "/Users/runner/work/static-frame/static-frame/static_frame/test/property/test_util.py", line 329, in test_setdiff1d
    def test_setdiff1d(self, arrays: tp.Sequence[np.ndarray]) -> None:
  File "/Users/runner/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/hypothesis/core.py", line 1203, in wrapped_test
    raise the_error_hypothesis_found
  File "/Users/runner/work/static-frame/static-frame/static_frame/test/property/test_util.py", line 334, in test_setdiff1d
    post = util.setdiff1d(
  File "/Users/runner/work/static-frame/static-frame/static_frame/core/util.py", line 2832, in setdiff1d
    return _ufunc_set_1d(np.setdiff1d,
  File "/Users/runner/work/static-frame/static-frame/static_frame/core/util.py", line 2640, in _ufunc_set_1d
    post = func(array, other, assume_unique=assume_unique) #type: ignore
  File "/Users/runner/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/numpy/lib/arraysetops.py", line 981, in setdiff1d
    return ar1[in1d(ar1, ar2, assume_unique=True, invert=True)]
  File "/Users/runner/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/numpy/lib/arraysetops.py", line 699, in in1d
    outgoing_array[basic_mask] = isin_helper_ar[ar1[basic_mask] -
IndexError: arrays used as indices must be of integer (or boolean) type
---------------------------------- Hypothesis ----------------------------------
Falsifying example: test_setdiff1d(
    arrays=[array([0], dtype=uint64), array([-1], dtype=int16)],
    self=<static_frame.test.property.test_util.TestUnit testMethod=test_setdiff1d>,
)

You can reproduce this example by temporarily adding @reproduce_failure('6.40.0', b'AAACAAMBAAEAAAAAAQABAQABAAE=') as a decorator on your test case

--------- coverage: platform darwin, python 3.10.13-final-0 ----------
Coverage XML written to file coverage.xml
```

**Comment by flexatone** [comment]
```
 ___________________________ TestUnit.test_frame_isin ___________________________
Traceback (most recent call last):
  File "/Users/runner/work/static-frame/static-frame/static_frame/test/property/test_frame.py", line 143, in test_frame_isin
    dtype_group=sfst.DTGroup.CORE_NO_OBJECT,
  File "/Users/runner/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/hypothesis/core.py", line 1203, in wrapped_test
    raise the_error_hypothesis_found
  File "/Users/runner/work/static-frame/static-frame/static_frame/test/property/test_frame.py", line 150, in test_frame_isin
    self.assertTrue(f1.isin((value,)).iloc[0, 0])
  File "/Users/runner/work/static-frame/static-frame/static_frame/core/frame.py", line 6310, in isin
    self._blocks.isin(other),
  File "/Users/runner/work/static-frame/static-frame/static_frame/core/type_blocks.py", line 3257, in isin
    return self.from_blocks(blocks())
  File "/Users/runner/work/static-frame/static-frame/static_frame/core/type_blocks.py", line 464, in from_blocks
    for block in raw_blocks:
  File "/Users/runner/work/static-frame/static-frame/static_frame/core/type_blocks.py", line 3251, in blocks
    yield isin_array(array=b,
  File "/Users/runner/work/static-frame/static-frame/static_frame/core/util.py", line 2990, in isin_array
    result = func(array, other, assume_unique=assume_unique)
  File "/Users/runner/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/numpy/lib/arraysetops.py", line 890, in isin
    return in1d(element, test_elements, assume_unique=assume_unique,
  File "/Users/runner/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/numpy/lib/arraysetops.py", line 699, in in1d
    outgoing_array[basic_mask] = isin_helper_ar[ar1[basic_mask] -
IndexError: arrays used as indices must be of integer (or boolean) type
---------------------------------- Hypothesis ----------------------------------
Falsifying example: test_frame_isin(
    f1=<Frame>
    <Index>   0                   1                   2      3      ā      Ă      <<U1>
    <Index>
    0.0       9223372036854775808 0                   0      0      0      0
    1.0       9223372036854775808 9223372036854775808 0      0      0      0
    -1.0      9223372036854775808 9223372036854775808 0      0      0      0
    2.0       9223372036854775808 9223372036854775808 0      0      0      0
    -2.0      9223372036854775808 9223372036854775808 0      0      0      0
    3.0       9223372036854775808 9223372036854775808 0      0      0      0
    <float64> <uint64>            <uint64>            <int8> <int8> <int8> <int8>,
    self=<static_frame.test.property.test_frame.TestUnit testMethod=test_frame_isin>,
)

You can reproduce this example by temporarily adding @reproduce_failure('6.40.0', b'AXicY2VlZMACkAQZEWwmhCgTQpSZgR2sg4mBmRFEM4IUMjGDdEIUNaAaCgATQgCy') as a decorator on your test case
```'

**Comment by flexatone** [comment]
```

You can reproduce this example by temporarily adding @reproduce_failure('6.92.1', b'AXicRZJdSJNhFMfPeT7fmZubWr3ookV+RHOrrCZl+bFEMhIUh7BBuKVt0IqKRCwwd2UQBV1EGO5OFIQUkZSSLoZ4ERI5sA8KwhINMwrpQpTCt3duzXN1Dv/D/znndx6QWQJACIIUAUxGTwMBbRW2gguI8CeJ6GXlDl5OUPuyJWCoGHEr630c4aZOf2M2wMg55bxzZjJkZWkDYjkLUBccnKvpubPY3OyvZKgtpyS1XrdL9XXf8hVy0NaT5vKozS3SGqUAtmSKe1yA8ZUeQ8M3dcBfD+i1L9/eiB75jCcsRguTJQIjuQvH+5cAagALZob/Og54babThQE7x4gIJiLkcxC8q2na/Op1V+bJ8rxKTM/kt9N0Gz/orCgrtumr1voO9yltA7slhY/f37+KekquMBeGiAS45h368WZW3ewqRYzFU0M64cJOAVqqDFZLiq0jsy+nx551iGPFGUpn9fbiOZKgO+p5NDc+aicmCNvEfwpQQVFbSsIHnbVq2q8brQ9tuLMfxGvMvMvXGioF7G70rv3avFFvNuyTDC0DfR+eTw8Om41N4QKWthIGSWv1NVPlDqpC9y5dTh0zI6tqG3cOgK+IJY+bOBOFAJMEzminKAE2ZmeIf/zubCSciYl3VYQjhd/tuvb6a5lO6OnPm0wwOsskMwDSt5yM6t9oUkoktRK5Q6d2j5Awwid93KwWrySin/JMhvkd83vzVPNyAARfA2SKYDFEpekyQ9P9i0B4p2RSWGwVassLZWIRRb5AxdqPklylYpTqD+QuxszOFWQLCRBWV06D3fpwyFI3ZZxqI/wQAGNFlLRzOk5IIyGX4B+veLR0') as a decorator on your test case
______________________ TestUnit.test_array_set_ufunc_many ______________________
  + Exception Group Traceback (most recent call last):
  |   File "/Users/runner/work/static-frame/static-frame/static_frame/test/property/test_util.py", line 413, in test_array_set_ufunc_many
  |     def test_array_set_ufunc_many(self, arrays: tp.Sequence[np.ndarray]) -> None:
  |   File "/Users/runner/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/hypothesis/core.py", line 1588, in wrapped_test
  |     raise the_error_hypothesis_found
  | exceptiongroup.ExceptionGroup: Hypothesis found 2 distinct failures. (2 sub-exceptions)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/Users/runner/work/static-frame/static-frame/static_frame/test/property/test_util.py", line 421, in test_array_set_ufunc_many
    |     post = util.ufunc_set_iter(arrays, many_to_one_type=mtot)
    |   File "/Users/runner/work/static-frame/static-frame/static_frame/core/util.py", line 2920, in ufunc_set_iter
    |     result = ufunc(result, array, assume_unique=assume_unique)
    |   File "/Users/runner/work/static-frame/static-frame/static_frame/core/util.py", line 2847, in union2d
    |     return _ufunc_set_2d(np.union1d,
    |   File "/Users/runner/work/static-frame/static-frame/static_frame/core/util.py", line 2742, in _ufunc_set_2d
    |     result = array_set | other_set
    | TypeError: Cannot get a common metadata divisor for Numpy datetime metadata [Y] and [D] because they have incompatible nonlinear base time units.
    | Falsifying example: test_array_set_ufunc_many(
    |     self=<static_frame.test.property.test_util.TestUnit testMethod=test_array_set_ufunc_many>,
    |     arrays=[array_map(<...>), array_map(<...>), array_map(<...>)],
    | )
    | 
    | You can reproduce this example by temporarily adding @reproduce_failure('6.92.1', b'AXicY2BkYGZAA4wMbHAWhMcE5zEAAAI1ABc=') as a decorator on your test case
    +---------------- 2 ----------------
    | Traceback (most recent call last):
    |   File "/Users/runner/work/static-frame/static-frame/static_frame/test/property/test_util.py", line 421, in test_array_set_ufunc_many
    |     post = util.ufunc_set_iter(arrays, many_to_one_type=mtot)
    |   File "/Users/runner/work/static-frame/static-frame/static_frame/core/util.py", line 2920, in ufunc_set_iter
    |     result = ufunc(result, array, assume_unique=assume_unique)
    |   File "/Users/runner/work/static-frame/static-frame/static_frame/core/util.py", line 2860, in intersect2d
    |     return _ufunc_set_2d(np.intersect1d,
    |   File "/Users/runner/work/static-frame/static-frame/static_frame/core/util.py", line 2744, in _ufunc_set_2d
    |     result = array_set & other_set
    | TypeError: Cannot get a common metadata divisor for Numpy datetime metadata [Y] and [D] because they have incompatible nonlinear base time units.
    | Falsifying example: test_array_set_ufunc_many(
    |     self=<static_frame.test.property.test_util.TestUnit testMethod=test_array_set_ufunc_many>,
    |     arrays=[array_map(<...>), array_map(<...>), array_map(<...>)],
    | )
    | 
    | You can reproduce this example by temporarily adding @reproduce_failure('6.92.1', b'AXicY2BkAANGBjYGGAvCY4LzGAABkwAU') as a decorator on your test case
    +------------------------------------
```

**Comment by flexatone** [comment]
____________________________ TestUnit.test_union2d _____________________________
Traceback (most recent call last):
  File "/home/runner/work/static-frame/static-frame/static_frame/test/property/test_util.py", line 366, in test_union2d
    def test_union2d(self, arrays: tp.Sequence[np.ndarray]) -> None:
               ^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/hypothesis/core.py", line 1588, in wrapped_test
    raise the_error_hypothesis_found
  File "/home/runner/work/static-frame/static-frame/static_frame/test/property/test_util.py", line 377, in test_union2d
    self.assertTrue(len(post) == len(
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/unittest/case.py", line 715, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
Falsifying example: test_union2d(
    self=<static_frame.test.property.test_util.TestUnit testMethod=test_union2d>,
    arrays=[array_map(<...>), array_map(<...>)],
)

You can reproduce this example by temporarily adding @reproduce_failure('6.92.1', b'AXicY2BgZWBkQAVAEZAQI0MDVAAABXEAjw==') as a decorator on your test case

**Comment by flexatone** [comment]
```
 ______________________ TestUnit.test_array_set_ufunc_many ______________________
  + Exception Group Traceback (most recent call last):
  |   File "/home/runner/work/static-frame/static-frame/static_frame/test/property/test_util.py", line 413, in test_array_set_ufunc_many
  |     def test_array_set_ufunc_many(self, arrays: tp.Sequence[np.ndarray]) -> None:
  |                ^^^^^^^
  |   File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/hypothesis/core.py", line 1588, in wrapped_test
  |     raise the_error_hypothesis_found
  | ExceptionGroup: Hypothesis found 2 distinct failures. (2 sub-exceptions)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/runner/work/static-frame/static-frame/static_frame/test/property/test_util.py", line 421, in test_array_set_ufunc_many
    |     post = util.ufunc_set_iter(arrays, many_to_one_type=mtot)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/runner/work/static-frame/static-frame/static_frame/core/util.py", line 2920, in ufunc_set_iter
    |     result = ufunc(result, array, assume_unique=assume_unique)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/runner/work/static-frame/static-frame/static_frame/core/util.py", line 2847, in union2d
    |     return _ufunc_set_2d(np.union1d,
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/runner/work/static-frame/static-frame/static_frame/core/util.py", line 2742, in _ufunc_set_2d
    |     result = array_set | other_set
    |              ~~~~~~~~~~^~~~~~~~~~~
    | TypeError: Cannot get a common metadata divisor for Numpy datetime metadata [Y] and [D] because they have incompatible nonlinear base time units.
    | Falsifying example: test_array_set_ufunc_many(
    |     self=<static_frame.test.property.test_util.TestUnit testMethod=test_array_set_ufunc_many>,
    |     arrays=[array_map(<...>), array_map(<...>), array_map(<...>)],
    | )
    | 
    | You can reproduce this example by temporarily adding @reproduce_failure('6.92.1', b'AXicY2BkYGNAA4wwio2BCSEAAAHLABM=') as a decorator on your test case
    +---------------- 2 ----------------
    | Traceback (most recent call last):
    |   File "/home/runner/work/static-frame/static-frame/static_frame/test/property/test_util.py", line 421, in test_array_set_ufunc_many
    |     post = util.ufunc_set_iter(arrays, many_to_one_type=mtot)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/runner/work/static-frame/static-frame/static_frame/core/util.py", line 2920, in ufunc_set_iter
    |     result = ufunc(result, array, assume_unique=assume_unique)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/runner/work/static-frame/static-frame/static_frame/core/util.py", line 2860, in intersect2d
    |     return _ufunc_set_2d(np.intersect1d,
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/runner/work/static-frame/static-frame/static_frame/core/util.py", line 2744, in _ufunc_set_2d
    |     result = array_set & other_set
    |              ~~~~~~~~~~^~~~~~~~~~~
    | TypeError: Cannot get a common metadata divisor for Numpy datetime metadata [Y] and [D] because they have incompatible nonlinear base time units.
    | Falsifying example: test_array_set_ufunc_many(
    |     self=<static_frame.test.property.test_util.TestUnit testMethod=test_array_set_ufunc_many>,
    |     arrays=[array_map(<...>), array_map(<...>), array_map(<...>)],
    | )
    | 
    | You can reproduce this example by temporarily adding @reproduce_failure('6.92.1', b'AXicY2BkAANGBjYGNAASYoKygAAAAa0AEw==') as a decorator on your test case
```

**Comment by flexatone** [comment]
```
=================================== FAILURES ===================================
______________________ TestUnit.test_array_set_ufunc_many ______________________
  + Exception Group Traceback (most recent call last):
  |   File "/home/runner/work/static-frame/static-frame/static_frame/test/property/test_util.py", line 413, in test_array_set_ufunc_many
  |     def test_array_set_ufunc_many(self, arrays: tp.Sequence[np.ndarray]) -> None:
  |   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/hypothesis/core.py", line 1588, in wrapped_test
  |     raise the_error_hypothesis_found
  | exceptiongroup.ExceptionGroup: Hypothesis found 2 distinct failures. (2 sub-exceptions)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/runner/work/static-frame/static-frame/static_frame/test/property/test_util.py", line 421, in test_array_set_ufunc_many
    |     post = util.ufunc_set_iter(arrays, many_to_one_type=mtot)
    |   File "/home/runner/work/static-frame/static-frame/static_frame/core/util.py", line 2920, in ufunc_set_iter
    |     result = ufunc(result, array, assume_unique=assume_unique)
    |   File "/home/runner/work/static-frame/static-frame/static_frame/core/util.py", line 2847, in union2d
    |     return _ufunc_set_2d(np.union1d,
    |   File "/home/runner/work/static-frame/static-frame/static_frame/core/util.py", line 2742, in _ufunc_set_2d
    |     result = array_set | other_set
    | TypeError: Cannot get a common metadata divisor for Numpy datetime metadata [Y] and [D] because they have incompatible nonlinear base time units.
    | Falsifying example: test_array_set_ufunc_many(
    |     self=<static_frame.test.property.test_util.TestUnit testMethod=test_array_set_ufunc_many>,
    |     arrays=[array_map(<...>),
    |      array_map(<...>),
    |      array_map(<...>),
    |      array_map(<...>),
    |      array_map(<...>),
    |      array_map(<...>)],
    | )
    | 
    | You can reproduce this example by temporarily adding @reproduce_failure('6.92.1', b'AXicY2BkAAMcFBsDXIAJxGOC8xgAAmIAGw==') as a decorator on your test case
    +---------------- 2 ----------------
    | Traceback (most recent call last):
    |   File "/home/runner/work/static-frame/static-frame/static_frame/test/property/test_util.py", line 421, in test_array_set_ufunc_many
    |     post = util.ufunc_set_iter(arrays, many_to_one_type=mtot)
    |   File "/home/runner/work/static-frame/static-frame/static_frame/core/util.py", line 2920, in ufunc_set_iter
    |     result = ufunc(result, array, assume_unique=assume_unique)
    |   File "/home/runner/work/static-frame/static-frame/static_frame/core/util.py", line 2860, in intersect2d
    |     return _ufunc_set_2d(np.intersect1d,
    |   File "/home/runner/work/static-frame/static-frame/static_frame/core/util.py", line 2744, in _ufunc_set_2d
    |     result = array_set & other_set
    | TypeError: Cannot get a common metadata divisor for Numpy datetime metadata [Y] and [D] because they have incompatible nonlinear base time units.
    | Falsifying example: test_array_set_ufunc_many(
    |     self=<static_frame.test.property.test_util.TestUnit testMethod=test_array_set_ufunc_many>,
    |     arrays=[array_map(<...>),
    |      array_map(<...>),
    |      array_map(<...>),
    |      array_map(<...>),
    |      array_map(<...>),
    |      array_map(<...>)],
    | )
    | 
    | You can reproduce this example by temporarily adding @reproduce_failure('6.92.1', b'AXicY2BkAAMcFBsDQgDEY0JIAwACPgAX') as a decorator on your test case
    +------------------------------------

---------- coverage: platform linux, python 3.9.18-final-0 -----------
```

**Comment by flexatone** [comment]
```
___________________________ TestUnit.test_setdiff1d ____________________________
Traceback (most recent call last):
  File "/home/runner/work/static-frame/static-frame/static_frame/test/property/test_util.py", line 332, in test_setdiff1d
    def test_setdiff1d(self, arrays: tp.Sequence[np.ndarray]) -> None:
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/hypothesis/core.py", line 1588, in wrapped_test
    raise the_error_hypothesis_found
  File "/home/runner/work/static-frame/static-frame/static_frame/test/property/test_util.py", line 357, in test_setdiff1d
    self.assertTrue(len(post) == len(set(arrays[0]).difference(set(arrays[1]))))
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/unittest/case.py", line 687, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
Falsifying example: test_setdiff1d(
    self=<static_frame.test.property.test_util.TestUnit testMethod=test_setdiff1d>,
    arrays=[array_map(<...>), array_map(<...>)],
)

You can reproduce this example by temporarily adding @reproduce_failure('6.92.1', b'AXicY2BlYGBiZGBgZGhggAEkNlCWAQAUZwEQ') as a decorator on your test case
```

**Comment by flexatone** [comment]
```

=================================== FAILURES ===================================
____________________ TestUnit.test_binary_operators_numeric ____________________
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/hypothesis/core.py", line 988, in _execute_once_for_engine
    result = self.execute_once(data)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/hypothesis/core.py", line 928, in execute_once
    result = self.test_runner(data, run)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/hypothesis/core.py", line 729, in default_executor
    return function(data)
           ^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/hypothesis/core.py", line 919, in run
    return test(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/work/static-frame/static-frame/static_frame/test/property/test_frame.py", line 88, in test_binary_operators_numeric
    self.assertAlmostEqualArray(a, b)
  File "/Users/runner/work/static-frame/static-frame/static_frame/test/test_case.py", line 304, in assertAlmostEqualArray
    np.testing.assert_allclose(a1, a2)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/testing/_private/utils.py", line 1504, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/testing/_private/utils.py", line 718, in assert_array_compare
    flagged = func_assert_same_pos(x, y, func=isnan, hasval='nan')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/testing/_private/utils.py", line 688, in func_assert_same_pos
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

x and y nan location mismatch:
 x: array([[   0.   +0.j,    0.   +0.j,    0.   +0.j,   -2.25 +0.j,
        -225.   +0.j,   -2.25 +0.j],
       [  -2.25 +0.j,   -2.25 +0.j,   -2.25 +0.j,   -1.   +0.j,...
 y: array([[   0.   +0.j,    0.   +0.j,    0.   +0.j,   -2.25 +0.j,
        -225.   +0.j,   -2.25 +0.j],
       [  -2.25 +0.j,   -2.25 +0.j,   -2.25 +0.j,   -1.   +0.j,...

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/runner/work/static-frame/static-frame/static_frame/test/property/test_frame.py", line 67, in test_binary_operators_numeric
    def test_binary_operators_numeric(self, f1: Frame) -> None:
               ^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/hypothesis/core.py", line 1588, in wrapped_test
    raise the_error_hypothesis_found
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/hypothesis/core.py", line 952, in execute_once
    raise Flaky(
hypothesis.errors.Flaky: Hypothesis test_binary_operators_numeric(self=<static_frame.test.property.test_frame.TestUnit testMethod=test_binary_operators_numeric>, f1=<Frame>
<Index> 0            1                    22           2            -1           3            <int8>
<Index>
0       0j           0j                   0j           1.5j         15j          1.5j
-2      1.5j         1.5j                 1.5j         1j           1.5j         1.5j
6       1.5j         1.5j                 1.5j         1.5j         1.5j         1.5j
1       1.5j         1.5j                 1.5j         1.5j         1.5j         1.5j
2       1.5j         1.5j                 1.5j         1.5j         1.5j         1.5j
25      1.5j         1.5j                 1.5j         1.5j         1.5j         1.5j
-1      1.5j         1.5j                 1.5j         1.5j         1.5j         1.5j
-54     1.5j         -1.80e+308-1.80e+... 1.5j         1.5j         1.5j         1.5j
<int8>  <complex128> <complex128>         <complex128> <complex128> <complex128> <complex128>) produces unreliable results: Falsified on the first call but did not on a subsequent one
Falsifying example: test_binary_operators_numeric(
    self=<static_frame.test.property.test_frame.TestUnit testMethod=test_binary_operators_numeric>,
    f1=Frame(
        from_blocks((array_map(<...>),)),
        index=Index(array_map(<...>)),
        columns=Index(array_map(<...>)),
    ),
)
Failed to reproduce exception. Expected: 
Traceback (most recent call last):
  File "/Users/runner/work/static-frame/static-frame/static_frame/test/property/test_frame.py", line 88, in test_binary_operators_numeric
    self.assertAlmostEqualArray(a, b)
  File "/Users/runner/work/static-frame/static-frame/static_frame/test/test_case.py", line 304, in assertAlmostEqualArray
    np.testing.assert_allclose(a1, a2)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/testing/_private/utils.py", line 1504, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/testing/_private/utils.py", line 718, in assert_array_compare
    flagged = func_assert_same_pos(x, y, func=isnan, hasval='nan')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/testing/_private/utils.py", line 688, in func_assert_same_pos
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

x and y nan location mismatch:
 x: array([[   0.   +0.j,    0.   +0.j,    0.   +0.j,   -2.25 +0.j,
        -225.   +0.j,   -2.25 +0.j],
       [  -2.25 +0.j,   -2.25 +0.j,   -2.25 +0.j,   -1.   +0.j,...
 y: array([[   0.   +0.j,    0.   +0.j,    0.   +0.j,   -2.25 +0.j,
        -225.   +0.j,   -2.25 +0.j],
       [  -2.25 +0.j,   -2.25 +0.j,   -2.25 +0.j,   -1.   +0.j,...


You can reproduce this example by temporarily adding @reproduce_failure('6.92.1', b'AXicY2BnZWBgZmYEEpwM2AAjKwMjE4KHkGBnYmTEJo4kisJh19ZjYNz/HwJ8GOFMPhZkDXDAz8+EJA5U04BqIshRbGCLmZgYJBlBwAymAUiLAcWBQkwMzAAWVxGY') as a decorator on your test case
---------------------------------- Hypothesis ----------------------------------
WARNING: Hypothesis has spent more than five minutes working to shrink a failing example, and stopped because it is making very slow progress.  When you re-run your tests, shrinking will resume and may take this long before aborting again.
PLEASE REPORT THIS if you can provide a reproducing example, so that we can improve shrinking performance for everyone.

---------- coverage: platform darwin, python 3.11.8-final-0 ----------
Coverage XML written to file coverage.xml
```

**Comment by flexatone** [comment]
______________________ TestUnit.test_array_set_ufunc_many ______________________
  + Exception Group Traceback (most recent call last):
  |   File "/home/runner/work/static-frame/static-frame/static_frame/test/property/test_util.py", line 413, in test_array_set_ufunc_many
  |     def test_array_set_ufunc_many(self, arrays: tp.Sequence[np.ndarray]) -> None:
  |                ^^^^^^^
  |   File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/hypothesis/core.py", line 1588, in wrapped_test
  |     raise the_error_hypothesis_found
  | ExceptionGroup: Hypothesis found 2 distinct failures. (2 sub-exceptions)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/runner/work/static-frame/static-frame/static_frame/test/property/test_util.py", line 421, in test_array_set_ufunc_many
    |     post = util.ufunc_set_iter(arrays, many_to_one_type=mtot)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/runner/work/static-frame/static-frame/static_frame/core/util.py", line 3123, in ufunc_set_iter
    |     result = ufunc(result, array, assume_unique=assume_unique)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/runner/work/static-frame/static-frame/static_frame/core/util.py", line 3050, in union2d
    |     return _ufunc_set_2d(np.union1d,
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/runner/work/static-frame/static-frame/static_frame/core/util.py", line 2945, in _ufunc_set_2d
    |     result = array_set | other_set
    |              ~~~~~~~~~~^~~~~~~~~~~
    | TypeError: Cannot get a common metadata divisor for Numpy datetime metadata [Y] and [D] because they have incompatible nonlinear base time units.
    | Falsifying example: test_array_set_ufunc_many(
    |     self=<static_frame.test.property.test_util.TestUnit testMethod=test_array_set_ufunc_many>,
    |     arrays=[array_map(<...>), array_map(<...>), array_map(<...>)],
    | )
    | 
    | You can reproduce this example by temporarily adding @reproduce_failure('6.92.1', b'AXicY2BkYGNAA4wwio2BCSEAAAHLABM=') as a decorator on your test case
    +---------------- 2 ----------------
    | Traceback (most recent call last):
    |   File "/home/runner/work/static-frame/static-frame/static_frame/test/property/test_util.py", line 421, in test_array_set_ufunc_many
    |     post = util.ufunc_set_iter(arrays, many_to_one_type=mtot)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/runner/work/static-frame/static-frame/static_frame/core/util.py", line 3123, in ufunc_set_iter
    |     result = ufunc(result, array, assume_unique=assume_unique)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/runner/work/static-frame/static-frame/static_frame/core/util.py", line 3063, in intersect2d
    |     return _ufunc_set_2d(np.intersect1d,
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/runner/work/static-frame/static-frame/static_frame/core/util.py", line 2947, in _ufunc_set_2d
    |     result = array_set & other_set
    |              ~~~~~~~~~~^~~~~~~~~~~
    | TypeError: Cannot get a common metadata divisor for Numpy datetime metadata [Y] and [D] because they have incompatible nonlinear base time units.
    | Falsifying example: test_array_set_ufunc_many(
    |     self=<static_frame.test.property.test_util.TestUnit testMethod=test_array_set_ufunc_many>,
    |     arrays=[array_map(<...>), array_map(<...>), array_map(<...>)],
    | )
    | 
    | You can reproduce this example by temporarily adding @reproduce_failure('6.92.1', b'AXicY2BkAANGBjYGNAASYoKygAAAAa0AEw==') as a decorator on your test case
    +------------------------------------

**Comment by flexatone** [comment]
Many of these are now resolved.
